# Generated by Django 2.0.3 on 2020-08-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0002_usertype_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userType',
        ),
    ]
