# Generated by Django 2.2.12 on 2020-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0003_delete_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientBookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('problems', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('massage', models.CharField(max_length=500)),
            ],
        ),
    ]
