# Generated by Django 2.2.12 on 2020-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0004_patientbookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbookappointment',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
