# Generated by Django 2.2.12 on 2020-08-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0005_auto_20200809_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype_table',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='bloodgroup',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype_table',
            name='postal',
            field=models.IntegerField(null=True),
        ),
    ]
