# Generated by Django 2.2.12 on 2020-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0008_auto_20200810_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype_table',
            name='phone',
            field=models.IntegerField(default=7607696965),
            preserve_default=False,
        ),
    ]
