# Generated by Django 2.2.12 on 2020-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0010_auto_20200812_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
